management:
  security:
    enabled: false
hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
			
spring:
  druid:
    druidClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-mdc?characterEncoding=utf8&useSSL=false
    maxActive: 30
    minIdle: 5
    maxWait: 10000
    validationgQuery: SELECT 'X'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
springcloud:
  dingTalk:
    webhookToken:
      sendException: 0fc2122c955fb9350ca5d840bbe592cd31158ae9dea3b6699d4063eecc402afa
      jobListener: 0fc2122c955fb9350ca5d840bbe592cd31158ae9dea3b6699d4063eecc402afa
	 	  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config:
    location: classpath:mybatis-config.xml
    