spring:
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_zipkin?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: paascloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql


