spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: SPRINGCLOUD-PROVIDER-CLAIMS
        uri: lb://SPRINGCLOUD-PROVIDER-CLAIMS
        predicates:
          - Path=/SPRINGCLOUD-PROVIDER-CLAIMS/**
        filters:
          - RewritePath=/SPRINGCLOUD-PROVIDER-CLAIMS/(?<path>.*), /$\{path}
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback
      - id: SPRINGCLOUD-PROVIDER-UNDERWRITE
        uri: lb://SPRINGCLOUD-PROVIDER-UNDERWRITE
        predicates:
          - Pach=/SPRINGCLOUD-PROVIDER-UNDERWRITE/**
        filters:
          - RewritePath=/SPRINGCLOUD-PROVIDER-UNDERWRITE/(?<path>.*), /$\{path}
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
feign:
  hystrix:
    enabled: true
hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    