spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_zipkin?characterEncoding=utf8&useSSL=false
    schema: classpath:/mysql.sql
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: paascloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql


